import { renderTabs } from './tabs.js';
import { renderPlusMinusButton } from './plus-minus-button.js';
import { renderMenuButton } from './menu-button.js';
import { buyproduct } from './buy-product.js';
import { renderNotification } from './notification.js';
import { renderformcheckout } from './form-checkout.js';
import { renderbuttonfaq } from './button-faq.js';
import { renderresponsive } from './responsive.js';
renderTabs();
renderPlusMinusButton();
renderMenuButton();
buyproduct();
renderNotification();
renderformcheckout();
renderbuttonfaq();
renderresponsive();